name: Release cli

on:
  workflow_dispatch:
    inputs:
      SPHA_CLI_VERSION:
        description: "CLI version"
        required: true
        type: string

jobs:
  publish-cli-gh:
    env:
      SPHA_CLI_VERSION: ${{ inputs.SPHA_CLI_VERSION }}
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    environment: Deploy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Apache Maven Central
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
      - name: Package cli distribution
        env:
          SPHA_CLI_VERSION: ${{ env.SPHA_CLI_VERSION }}
        run: |
          ./gradlew distZip
          mkdir -p release
          cp cli/build/distributions/*.zip release

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPHA_CLI_VERSION: ${{ env.SPHA_CLI_VERSION }}
        run: |
          gh release create "cli/$SPHA_CLI_VERSION" --title "cli: $SPHA_CLI_VERSION" --generate-notes release/*

  publish-cli-docker:
    env:
      SPHA_CLI_VERSION: ${{ inputs.SPHA_CLI_VERSION }}
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}/cli
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside PRs.
      id-token: write
      attestations: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@0567fa5ae8c9a197cb207537dc5cbb43ca3d803f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.SPHA_CLI_VERSION }}, priority=100
            type=raw,value=latest,priority=90

      # Build and push the Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          platforms: linux/amd64, linux/arm64
          file: "cli/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true